name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # cacheing
    - name: Cache local cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-local-bin-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-local-bin-
    - name: Cache global cargo bin
      uses: actions/cache@v1
      with:
        path: /usr/share/rust/.cargo/bin
        key: ${{ runner.os }}-cargo-global-bin-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-global-bin-
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: web-sys-examples/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-target-

    - name: build
      run: scripts/build.sh

    - name: release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        source scripts/ci.sh
        tag=`basename ${{ github.ref }}`
        create_release schell todo-mvc-bench ${{ secrets.GITHUB_TOKEN }} $tag || exit 1
        upload_release_file ${{ secrets.GITHUB_TOKEN }} release.tar.gz release.tar.gz || exit 1
